# Generated by Django 3.2.19 on 2023-12-03 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20231204_0001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mark',
            name='mark',
            field=models.IntegerField(default=1, verbose_name='Mark'),
            preserve_default=False,
        ),
    ]
